# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
gcc-7:
  docker:
    - image: conanio/gcc7
  steps:
    - checkout
    - run:
        name: Build Conan package
        command: |
          sudo pip install --upgrade conan
          mkdir build && cd build
          conan install .. --build=missing
          conan build ..
workflows:
  version: 2
  build_and_test:
    jobs:
    - gcc-7