# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs: 
  win: circleci/windows@2.4.0

commands:
  conan-build: 
    steps:
      - checkout
      - run:
          name: Build Conan package
          command: |
            conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
            mkdir build && cd build
            conan install .. --build=missing
            conan build ..

jobs:
  gcc-7_x64:
    docker:
      - image: conanio/gcc7
    steps:
      - run:
          name: Upgrade conan
          command: sudo pip install --upgrade conan
      - conan-build
  msvc-2019:
    executor: 
      name: win/default
    steps:
      - run:
          name: Upgrade conan
          command: pip install --upgrade conan
      - conan-build
workflows:
  version: 2.1
  build_and_test:
    jobs:
    - gcc-7_x64
    - msvc-2019