conan_build: &conan_build
  command: |
    sudo pip install --upgrade conan
    conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    mkdir build && cd build
    conan install .. --build=missing
    conan build ..

# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
commands:
  conan-build: 
    steps:
      - checkout
      - run:
          name: Build Conan package
          command: |
            pip install conan
            conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
            mkdir build && cd build
            conan install .. --build=missing
            conan build ..

jobs:
  gcc-7_x64:
    docker:
      - image: conanio/gcc7
    steps:
      - conan-build
  msvc-2019:
    orbs: 
      win: circleci/windows@2.2.0 
    steps:
      - conan-build
workflows:
  version: 2.1
  build_and_test:
    jobs:
    - gcc-7_x64
    - msvc-2019